package org.campagnelab.antlr.tomps.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myToOperator__BehaviorDescriptor = new ToOperator__BehaviorDescriptor();
  private final BHDescriptor myMapper__BehaviorDescriptor = new Mapper__BehaviorDescriptor();
  private final BHDescriptor myNewVisitor__BehaviorDescriptor = new NewVisitor__BehaviorDescriptor();
  private final BHDescriptor myOperator__BehaviorDescriptor = new Operator__BehaviorDescriptor();
  private final BHDescriptor myPropertyDestination__BehaviorDescriptor = new PropertyDestination__BehaviorDescriptor();
  private final BHDescriptor mySource__BehaviorDescriptor = new Source__BehaviorDescriptor();
  private final BHDescriptor myParserRuleSource__BehaviorDescriptor = new ParserRuleSource__BehaviorDescriptor();
  private final BHDescriptor myTextGenHelper__BehaviorDescriptor = new TextGenHelper__BehaviorDescriptor();
  private final BHDescriptor myToIntDestination__BehaviorDescriptor = new ToIntDestination__BehaviorDescriptor();
  private final BHDescriptor myToBooleanDestination__BehaviorDescriptor = new ToBooleanDestination__BehaviorDescriptor();
  private final BHDescriptor myToFloatDestination__BehaviorDescriptor = new ToFloatDestination__BehaviorDescriptor();
  private final BHDescriptor myLabeledElementSource__BehaviorDescriptor = new LabeledElementSource__BehaviorDescriptor();
  private final BHDescriptor myDestination__BehaviorDescriptor = new Destination__BehaviorDescriptor();
  private final BHDescriptor myChildDestination__BehaviorDescriptor = new ChildDestination__BehaviorDescriptor();
  private final BHDescriptor myLexerRuleSource__BehaviorDescriptor = new LexerRuleSource__BehaviorDescriptor();
  private final BHDescriptor myConceptMapper__BehaviorDescriptor = new ConceptMapper__BehaviorDescriptor();
  private final BHDescriptor myConvertToMPS__BehaviorDescriptor = new ConvertToMPS__BehaviorDescriptor();
  private final BHDescriptor myAlternativeMapper__BehaviorDescriptor = new AlternativeMapper__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (index_846f5o_a0v.index(cncpt)) {
      case 0:
        return myAlternativeMapper__BehaviorDescriptor;
      case 1:
        return myChildDestination__BehaviorDescriptor;
      case 2:
        return myConceptMapper__BehaviorDescriptor;
      case 3:
        return myConvertToMPS__BehaviorDescriptor;
      case 4:
        return myDestination__BehaviorDescriptor;
      case 5:
        return myLabeledElementSource__BehaviorDescriptor;
      case 6:
        return myLexerRuleSource__BehaviorDescriptor;
      case 7:
        return myMapper__BehaviorDescriptor;
      case 8:
        return myNewVisitor__BehaviorDescriptor;
      case 9:
        return myOperator__BehaviorDescriptor;
      case 10:
        return myParserRuleSource__BehaviorDescriptor;
      case 11:
        return myPropertyDestination__BehaviorDescriptor;
      case 12:
        return mySource__BehaviorDescriptor;
      case 13:
        return myTextGenHelper__BehaviorDescriptor;
      case 14:
        return myToBooleanDestination__BehaviorDescriptor;
      case 15:
        return myToFloatDestination__BehaviorDescriptor;
      case 16:
        return myToIntDestination__BehaviorDescriptor;
      case 17:
        return myToOperator__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex index_846f5o_a0v = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6a1bb02ea606232bL), MetaIdFactory.conceptId(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x4aaf5f3861bb9099L), MetaIdFactory.conceptId(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x69d936b00a0eba02L), MetaIdFactory.conceptId(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6a1bb02ea6061b82L), MetaIdFactory.conceptId(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x4aaf5f3861bb9098L), MetaIdFactory.conceptId(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x4aaf5f3861adfe77L), MetaIdFactory.conceptId(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6912564f422833dbL), MetaIdFactory.conceptId(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL), MetaIdFactory.conceptId(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x11106e6008e38ee7L), MetaIdFactory.conceptId(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x195a5f84d619bfbdL), MetaIdFactory.conceptId(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x3875e55a78eeb7feL), MetaIdFactory.conceptId(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x27b12e38d7577b90L), MetaIdFactory.conceptId(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x3875e55a78eeb7ddL), MetaIdFactory.conceptId(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x3ec2bbae1a5cc460L), MetaIdFactory.conceptId(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x443e8c43ffcc4608L), MetaIdFactory.conceptId(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x443e8c43ffcf6763L), MetaIdFactory.conceptId(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x443e8c43ffc0edbfL), MetaIdFactory.conceptId(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6c9855e848a0c58L)).seal();
}
