package org.campagnelab.ANTLR.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_Alternative = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Alternatives = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_BlockSet = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Dot = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Grammar = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_HasOptionalParams = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_LabeledElement = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_LexerAlt = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_LexerAltList = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_LexerBlock = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_LexerElement = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_LexerRule = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_LexerRuleBlock = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_LexerRuleRef = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_LexerRuleRefByName = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_LexerToken = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_NotSet = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Parentheses = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ParserRule = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ParserRuleBlock = new ConceptPresentationBuilder().deprecated(MetaAdapterFactory.getProperty(0xd6782141eafa4cf7L, 0xa85d1229abdb1152L, 0x631eebe31132d843L, 0x631eebe3113c4245L, "isOptional_old"), MetaAdapterFactory.getProperty(0xd6782141eafa4cf7L, 0xa85d1229abdb1152L, 0x631eebe31132d843L, 0x631eebe3113c4247L, "acceptMultiple_old"), MetaAdapterFactory.getProperty(0xd6782141eafa4cf7L, 0xa85d1229abdb1152L, 0x631eebe31132d843L, 0x72827882b897b9d5L, "plus_old")).create();
  private final ConceptPresentation props_ParserRuleRef = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_REGEXP = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Range = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Rule = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_RuleRefByName = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Sequence = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_SetElement = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_StringLiteral = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_ToTextOutput = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Token = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_TokenRef = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_TokenSpec = new ConceptPresentationBuilder().shortDesc("Specification for TOKENS").create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Alternative:
        return props_Alternative;
      case LanguageConceptSwitch.Alternatives:
        return props_Alternatives;
      case LanguageConceptSwitch.BlockSet:
        return props_BlockSet;
      case LanguageConceptSwitch.Dot:
        return props_Dot;
      case LanguageConceptSwitch.Grammar:
        return props_Grammar;
      case LanguageConceptSwitch.HasOptionalParams:
        return props_HasOptionalParams;
      case LanguageConceptSwitch.LabeledElement:
        return props_LabeledElement;
      case LanguageConceptSwitch.LexerAlt:
        return props_LexerAlt;
      case LanguageConceptSwitch.LexerAltList:
        return props_LexerAltList;
      case LanguageConceptSwitch.LexerBlock:
        return props_LexerBlock;
      case LanguageConceptSwitch.LexerElement:
        return props_LexerElement;
      case LanguageConceptSwitch.LexerRule:
        return props_LexerRule;
      case LanguageConceptSwitch.LexerRuleBlock:
        return props_LexerRuleBlock;
      case LanguageConceptSwitch.LexerRuleRef:
        return props_LexerRuleRef;
      case LanguageConceptSwitch.LexerRuleRefByName:
        return props_LexerRuleRefByName;
      case LanguageConceptSwitch.LexerToken:
        return props_LexerToken;
      case LanguageConceptSwitch.NotSet:
        return props_NotSet;
      case LanguageConceptSwitch.Parentheses:
        return props_Parentheses;
      case LanguageConceptSwitch.ParserRule:
        return props_ParserRule;
      case LanguageConceptSwitch.ParserRuleBlock:
        return props_ParserRuleBlock;
      case LanguageConceptSwitch.ParserRuleRef:
        return props_ParserRuleRef;
      case LanguageConceptSwitch.REGEXP:
        return props_REGEXP;
      case LanguageConceptSwitch.Range:
        return props_Range;
      case LanguageConceptSwitch.Rule:
        return props_Rule;
      case LanguageConceptSwitch.RuleRefByName:
        return props_RuleRefByName;
      case LanguageConceptSwitch.Sequence:
        return props_Sequence;
      case LanguageConceptSwitch.SetElement:
        return props_SetElement;
      case LanguageConceptSwitch.StringLiteral:
        return props_StringLiteral;
      case LanguageConceptSwitch.ToTextOutput:
        return props_ToTextOutput;
      case LanguageConceptSwitch.Token:
        return props_Token;
      case LanguageConceptSwitch.TokenRef:
        return props_TokenRef;
      case LanguageConceptSwitch.TokenSpec:
        return props_TokenSpec;
    }
    return null;
  }
}
